"""add client column  is_active bool

Revision ID: 0be56e1eb399
Revises: 6f24abfe1651
Create Date: 2026-09-30 12:36:49.601456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be56e1eb399'
down_revision: Union[str, Sequence[str], None] = '6f24abfe1651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
